### ISSUE TITLE
Doesn't escape arguments properly

### ISSUE THREAD

**Issue by BrandonArp** [KoskiLabs/jdk-wrapper#17] opened 2018-05-03 00:35 UTC
When passing arguments to the application being executed, they appear to be parsed and reinterpreted.  For instance:
`
./jdk-wrapper.sh sbt 'testOnly com.some.TestClass' 
`

gets changed to invoking
`
sbt "testOnly" "com.some.TestClass"
`

**Comment by vjkoskela** [comment] 2018-05-03 02:35
I believe this is a duplicate of #13; please confirm it's fixed in master (details in #13 on how to run) and re-open if this is still an issue.

**Closed by vjkoskela** 2018-05-03 02:35 UTC
